DELETE http://localhost:3001/api/users/644fd16ae36b80b202e8de52
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGZkMTZhZTM2YjgwYjIwMmU4ZGU1MiIsInVzZXJOYW1lIjoiUGVwaXRvIiwiaWF0IjoxNjgyOTUyNTc3LCJleHAiOjE2ODM1NTczNzd9.0PQhkaaLpqI9soshOOzs0eNWjRSo4JADA1vcPO2ckdA