PATCH http://localhost:3000/api/users/6488d34974fd5c19d1dc99e5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODhkMzQ5NzRmZDVjMTlkMWRjOTllNSIsInVzZXJOYW1lIjoiQWFyw7NuIEFyYWfDs24gQXJvY2EiLCJpYXQiOjE2ODY2ODg1ODUsImV4cCI6MTY4NzI5MzM4NX0.o1Kib7inF5HaIv452p0hpeER5AhnUgRnfQ4-Gwe3faY

{
  "userName": "Aarón Aragón Arocasss",
  "email": "aa@gmail.com",
  "firstName": "Aarón",
  "lastName": "Aragón Aroca"
}