POST http://localhost:3001/api/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NGZiZDExZDQ1MzgxMDBjNDMxNzMzOCIsInVzZXJOYW1lIjoiRXN0cmVsbGEiLCJpYXQiOjE2ODI5NTk2NzEsImV4cCI6MTY4MzU2NDQ3MX0.IOKDeFC9kgBll18WULTXuCi0YMaZ2BIhxdKyjYFQRs8

{
  "title": "Curso de desarrollo frontend 222",
  "description": " descripcion curso",
  "categoryId": "644fe46b14225c5c0564e764"
}