DELETE http://localhost:3000/api/courses/644fedcfeda2a559ca782323
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTdiZDc1Yjk4MTJiZTRhZmI2NjYyYyIsInVzZXJOYW1lIjoiQXJva2EiLCJpYXQiOjE2ODU5OTEwMzQsImV4cCI6MTY4NjU5NTgzNH0.3dDcR3R21sAbLjm6wMAHbiaFTtsSSQJI9aRH8O6KMgo