PATCH http://localhost:3001/api/courses/644fd44e76841903d0e595f1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTdiZDc1Yjk4MTJiZTRhZmI2NjYyYyIsInVzZXJOYW1lIjoiQXJva2EiLCJpYXQiOjE2ODU5OTEwMzQsImV4cCI6MTY4NjU5NTgzNH0.3dDcR3R21sAbLjm6wMAHbiaFTtsSSQJI9aRH8O6KMgo

{
  "title":"Actualizado"
}