DELETE http://localhost:3000/api/categories/648750ee74fd5c19d1dc99ce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTdiZDc1Yjk4MTJiZTRhZmI2NjYyYyIsInVzZXJOYW1lIjoiQXJva2EiLCJpYXQiOjE2ODY5NTE4OTMsImV4cCI6MTY4NzU1NjY5M30.jipb9gyeh5RrC5gt4hOKkF9Xr7lu6sXtT2TSHxJjFis