POST http://localhost:3000/api/lessons/647e360a07ffe8dbd50d64be
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTdiZDc1Yjk4MTJiZTRhZmI2NjYyYyIsInVzZXJOYW1lIjoiQXJva2EiLCJpYXQiOjE2ODY1ODk3MDAsImV4cCI6MTY4NzE5NDUwMH0.YcxR1H8zTCvLbTCcCNt5ywaouTC3cPUkCJFmMystgfg

{
  "title": "Lección avanzada",
  "description": "Lección 3 del curso de Git",
  "url": "course2.png",
  "image": "course2.png"
}